module.exports = {
  purge: {
    content: [
      "./pages/**/*.{js,ts,jsx,tsx}",
      "./components/**/*.{js,ts,jsx,tsx}",
    ],
    safelist: [
      "text-red-500",
      "text-green-500",
      "text-yellow-500",
      "text-gray-500",
      "text-purple-500",
      "text-indigo-500",
      "text-blue-500",
      "text-pink-500",
      "border-red-400",
      "border-green-400",
      "border-yellow-400",
      "border-gray-400",
      "border-purple-400",
      "border-indigo-400",
      "border-blue-400",
      "border-pink-400",
      "bg-red-100",
      "bg-green-100",
      "bg-yellow-100",
      "bg-gray-100",
      "bg-purple-100",
      "bg-indigo-100",
      "bg-blue-100",
      "bg-pink-100",
      "hover:bg-red-200",
      "hover:bg-green-200",
      "hover:bg-yellow-200",
      "hover:bg-gray-200",
      "hover:bg-purple-200",
      "hover:bg-indigo-200",
      "hover:bg-blue-200",
      "hover:bg-pink-200",
    ],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
